version: '3'
services:
    redis:
      image: redis:alpine
      container_name: at_redis
      mem_limit: 256m
      ports:
        - "6379:6379"

    nginx:
      image: nginx:stable-alpine
      container_name: at_nginx
      mem_limit: 1g
      ports:
        - '8080:80'
      volumes:
        - .:/home
        - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./paas/server.locations:/etc/nginx/server.locations
      depends_on:
        - php
        - mysql
        
    mysql:
        image: mysql:8.0.40
        container_name: at_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        mem_limit: 4g
        command:
            --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
            --thread_stack=196608
            --innodb_buffer_pool_size=1073741824
            --innodb_log_file_size=268435456
            --innodb_flush_log_at_trx_commit=1
            --max_connections=112
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: at
            MYSQL_USER: at
            MYSQL_PASSWORD: at
        ports:
          - 42333:3306     

    php:
        build: .docker/php
        container_name: at_php
        volumes:
          - .:/home
        mem_limit: 1g
        depends_on:
          - mysql