[project]
name = "mcp-data-gouv-fr"
version = "0.0.1"
description = "A Model Context Protocol server official data from the french government"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Adrien Dulac", email = "adrien.dulac@beta.gouv.fr" },
]
keywords = ["time", "timezone", "mcp", "llm"]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "mcp>=1.6.0",
    "requests==2.32.3",
    "pydantic==2.11.2",
    "jinja2==3.1.6",
    "elasticsearch==8.17.2",
]

[project.scripts]
mcp-data-gouv-fr = "mcp_data_gouv_fr:main"

