version: '3'

services:
  pdf_app:
    container_name: pdf_app
    restart: always
    build: ./front
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.enableCORS=false --server.enableXsrfProtection=false --server.enableWebsocketCompression=false

