services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes:
      - dbvol:/var/lib/postgresql/data

volumes:
  dbvol:
    driver: local
